# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c666e506d7c1fd18c54e3b7a92d4a47505f7c42ecb9e2e1df35d8084a9b6a08cbc9a11dc74083a6cb1e7d721ac8346436dbe80f210d3b02c5c75a9ed47425bcf

test:
  secret_key_base: 083c9f0a24b0f5e3a91c287fe7c819521c9da57827fb189d3a57a28c5db92abd60c7f2e102d6c1354c66b476001917f33555254b680b1fd30ecc9762ae098b9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
